name: Cypress E2E on Chrome

on: push

jobs:
  cypress-run:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: production
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.1

      - run: yarn install

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn dev
          wait-on: 'http://localhost:3000/'
          record: true
          parallel: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
